### ISSUE TITLE
Licence request

### ISSUE THREAD

**Issue by timtjtim** [konomae/pkcs7-php#2]
Hi,

I’d really like to use this in my code, but it need to be MIT or Apache 2.0 (or equivalent) licence for me to do so.

Would you be willing to add a licence to this package? I’m happy to do a pull request if that’s easier for you.

Thanks,
Tim

**Comment by konomae** [comment]
@timtjtim Thank you for considering using this package. 😀

This package is actually MIT license.
https://github.com/konomae/pkcs7-php/blob/master/composer.json#L5

I added the license file just in case.
https://github.com/konomae/pkcs7-php/commit/990297e6a045c1e973793b078663faa5a7495ef5

**Comment by timtjtim** [comment]
That’s great - my bad for not checking more thoroughly! Thanks for taking the time to clarify.
